name:                futr2
version:             0.1.0.0
github:              "githubuser/futr2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/futr2#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- aeson
- bytestring
- base16-bytestring
- vector 
- transformers
- utf8-string
- string-conversions

- wuss
- websockets
- modern-uri
- connection

- cryptonite
# - secp256k1-schnorr
- DRBG
- cipher-aes128
- cryptohash-sha256
- memory
# - libsecp256k1

- beam-core
- beam-sqlite
- beam-migrate
- sqlite-simple
  
- hspec

language: GHC2021

default-extensions: 
- RecordWildCards
- ViewPatterns
- BlockArguments
- OverloadedStrings
- LambdaCase

extra-lib-dirs: [//to/secp256k1/library]

ghc-options:
- -Wall

library:
  source-dirs: src
  pkg-config-dependencies:
  - libsecp256k1

executables:
  futr:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futr2

tests:
  futr2-test:
    main:                Spec.hs
    source-dirs:         test
    pkg-config-dependencies:
    - libsecp256k1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futr2
