name:                futr2
version:             0.1.0.0
github:              "autonomousorganization/futr2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description: "Walled gardens became prisons, and nostr is the first step towards tearing down the prison walls."      

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- time
- aeson
- bytestring
- base16-bytestring
- vector 
- utf8-string
- string-conversions
- containers

## concurrency 
- async  
- stm 

## sockets 
- wuss
- websockets
- modern-uri
- connection

## crypto
- DRBG
- cipher-aes128
- cryptohash-sha256
  
## database
- beam-core
- beam-sqlite
- beam-migrate
- sqlite-simple
  
- hspec

pkg-config-dependencies:
- libsecp256k1

language: GHC2021

default-extensions: 
- RecordWildCards
- ViewPatterns
- BlockArguments
- OverloadedStrings
- LambdaCase
- QuasiQuotes
- TemplateHaskell

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  futr:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futr2

tests:
  futr2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futr2
