
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/2.yaml

packages:
- .

extra-deps:
- git: https://github.com/AutonomousOrganization/beam # -- https://github.com/AutonomousOrganization/beam
  commit: a5eabfd0d6601135a18a334ffdea8ccc6ba68a11
  subdirs: 
    - beam-core
    - beam-sqlite
    - beam-migrate
- git: https://github.com/TomMD/cipher-aes128.git
  commit: 6f634f6c1ecb2b4173dbe4f46d269ee612c68840
- git: https://github.com/prolic/secp256k1-schnorr.git
  commit: 166b0d27d79e732731a54c7ec8e27e8f939cb6f5
- DRBG-0.5.5
- vector-sized-1.5.0  
