
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/9.yaml

packages:
- .

extra-deps:
- git: https://github.com/AutonomousOrganization/beam # -- https://github.com/AutonomousOrganization/beam
  commit: a5eabfd0d6601135a18a334ffdea8ccc6ba68a11
  subdirs: 
    - beam-core
    - beam-sqlite
    - beam-migrate
