
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/20.yaml

packages:
- .

extra-deps:
- clplug-0.4.0.0
- monomer-1.5.1.0
- monomer-hagrid-0.3.1.1
- git: https://github.com/AutonomousOrganization/beam # -- https://github.com/AutonomousOrganization/beam
  commit: fee04061cfcb93b3b4df6a0df8b0c7d8230d94f7
  subdirs: 
    - beam-core
    - beam-sqlite
    - beam-migrate
