
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/9.yaml

packages:
- .

extra-deps:
- git: https://github.com/AutonomousOrganization/beam # -- https://github.com/AutonomousOrganization/beam
  commit: 2e83ecf2388e3ed8047ad531706afe011c29c51c
  subdirs: 
    - beam-core
    - beam-sqlite
    - beam-migrate
